packages:
  - apps/*
  - packages/*
catalog:
  react: 19.1.0
  react-dom: 19.1.0
  tailwindcss: ^4.1.3
  tailwind-merge: ^3.3.1
  convex: ^1.27.0
  better-auth: 1.3.27
  "@convex-dev/better-auth": ^0.9.1
  "@types/react": ~19.1.11
  "@types/react-dom": ~19.1.7
  typescript: ^5.7.2
  "@better-auth/expo": 1.3.27
  "@types/node": ^24.10.0
