/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthenticatedRouteImport } from './routes/_unauthenticated'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as UnauthenticatedVerifyEmailRouteImport } from './routes/_unauthenticated/verify-email'
import { Route as UnauthenticatedSignupRouteImport } from './routes/_unauthenticated/signup'
import { Route as UnauthenticatedResetPasswordRouteImport } from './routes/_unauthenticated/reset-password'
import { Route as UnauthenticatedLoginRouteImport } from './routes/_unauthenticated/login'
import { Route as UnauthenticatedForgotPasswordRouteImport } from './routes/_unauthenticated/forgot-password'
import { Route as AuthenticatedTournamentsRouteImport } from './routes/_authenticated/tournaments'
import { Route as AuthenticatedPlayersRouteImport } from './routes/_authenticated/players'
import { Route as AuthenticatedDiscoverRouteImport } from './routes/_authenticated/discover'
import { Route as AuthenticatedUsernameRouteImport } from './routes/_authenticated/$username'
import { Route as AuthenticatedVenuesIndexRouteImport } from './routes/_authenticated/venues/index'
import { Route as AuthenticatedTournamentsIndexRouteImport } from './routes/_authenticated/tournaments/index'
import { Route as AuthenticatedPlayersIndexRouteImport } from './routes/_authenticated/players/index'
import { Route as AuthenticatedFeedIndexRouteImport } from './routes/_authenticated/feed/index'
import { Route as AuthenticatedVenuesNewRouteImport } from './routes/_authenticated/venues/new'
import { Route as AuthenticatedVenuesIdRouteImport } from './routes/_authenticated/venues/$id'
import { Route as AuthenticatedTournamentsNewRouteImport } from './routes/_authenticated/tournaments/new'
import { Route as AuthenticatedTournamentsIdRouteImport } from './routes/_authenticated/tournaments/$id'
import { Route as AuthenticatedPlayersIdRouteImport } from './routes/_authenticated/players/$id'
import { Route as ApiAuthSplatSplatRouteImport } from './routes/api/auth/$/$'

const UnauthenticatedRoute = UnauthenticatedRouteImport.update({
  id: '/_unauthenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const UnauthenticatedVerifyEmailRoute =
  UnauthenticatedVerifyEmailRouteImport.update({
    id: '/verify-email',
    path: '/verify-email',
    getParentRoute: () => UnauthenticatedRoute,
  } as any)
const UnauthenticatedSignupRoute = UnauthenticatedSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => UnauthenticatedRoute,
} as any)
const UnauthenticatedResetPasswordRoute =
  UnauthenticatedResetPasswordRouteImport.update({
    id: '/reset-password',
    path: '/reset-password',
    getParentRoute: () => UnauthenticatedRoute,
  } as any)
const UnauthenticatedLoginRoute = UnauthenticatedLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => UnauthenticatedRoute,
} as any)
const UnauthenticatedForgotPasswordRoute =
  UnauthenticatedForgotPasswordRouteImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => UnauthenticatedRoute,
  } as any)
const AuthenticatedTournamentsRoute =
  AuthenticatedTournamentsRouteImport.update({
    id: '/tournaments',
    path: '/tournaments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlayersRoute = AuthenticatedPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDiscoverRoute = AuthenticatedDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsernameRoute = AuthenticatedUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVenuesIndexRoute =
  AuthenticatedVenuesIndexRouteImport.update({
    id: '/venues/',
    path: '/venues/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTournamentsIndexRoute =
  AuthenticatedTournamentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTournamentsRoute,
  } as any)
const AuthenticatedPlayersIndexRoute =
  AuthenticatedPlayersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPlayersRoute,
  } as any)
const AuthenticatedFeedIndexRoute = AuthenticatedFeedIndexRouteImport.update({
  id: '/feed/',
  path: '/feed/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVenuesNewRoute = AuthenticatedVenuesNewRouteImport.update({
  id: '/venues/new',
  path: '/venues/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVenuesIdRoute = AuthenticatedVenuesIdRouteImport.update({
  id: '/venues/$id',
  path: '/venues/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTournamentsNewRoute =
  AuthenticatedTournamentsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedTournamentsRoute,
  } as any)
const AuthenticatedTournamentsIdRoute =
  AuthenticatedTournamentsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedTournamentsRoute,
  } as any)
const AuthenticatedPlayersIdRoute = AuthenticatedPlayersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedPlayersRoute,
} as any)
const ApiAuthSplatSplatRoute = ApiAuthSplatSplatRouteImport.update({
  id: '/api/auth/$/$',
  path: '/api/auth/$/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/$username': typeof AuthenticatedUsernameRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/players': typeof AuthenticatedPlayersRouteWithChildren
  '/tournaments': typeof AuthenticatedTournamentsRouteWithChildren
  '/forgot-password': typeof UnauthenticatedForgotPasswordRoute
  '/login': typeof UnauthenticatedLoginRoute
  '/reset-password': typeof UnauthenticatedResetPasswordRoute
  '/signup': typeof UnauthenticatedSignupRoute
  '/verify-email': typeof UnauthenticatedVerifyEmailRoute
  '/': typeof AuthenticatedIndexRoute
  '/players/$id': typeof AuthenticatedPlayersIdRoute
  '/tournaments/$id': typeof AuthenticatedTournamentsIdRoute
  '/tournaments/new': typeof AuthenticatedTournamentsNewRoute
  '/venues/$id': typeof AuthenticatedVenuesIdRoute
  '/venues/new': typeof AuthenticatedVenuesNewRoute
  '/feed': typeof AuthenticatedFeedIndexRoute
  '/players/': typeof AuthenticatedPlayersIndexRoute
  '/tournaments/': typeof AuthenticatedTournamentsIndexRoute
  '/venues': typeof AuthenticatedVenuesIndexRoute
  '/api/auth/$/$': typeof ApiAuthSplatSplatRoute
}
export interface FileRoutesByTo {
  '/$username': typeof AuthenticatedUsernameRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/forgot-password': typeof UnauthenticatedForgotPasswordRoute
  '/login': typeof UnauthenticatedLoginRoute
  '/reset-password': typeof UnauthenticatedResetPasswordRoute
  '/signup': typeof UnauthenticatedSignupRoute
  '/verify-email': typeof UnauthenticatedVerifyEmailRoute
  '/': typeof AuthenticatedIndexRoute
  '/players/$id': typeof AuthenticatedPlayersIdRoute
  '/tournaments/$id': typeof AuthenticatedTournamentsIdRoute
  '/tournaments/new': typeof AuthenticatedTournamentsNewRoute
  '/venues/$id': typeof AuthenticatedVenuesIdRoute
  '/venues/new': typeof AuthenticatedVenuesNewRoute
  '/feed': typeof AuthenticatedFeedIndexRoute
  '/players': typeof AuthenticatedPlayersIndexRoute
  '/tournaments': typeof AuthenticatedTournamentsIndexRoute
  '/venues': typeof AuthenticatedVenuesIndexRoute
  '/api/auth/$/$': typeof ApiAuthSplatSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_unauthenticated': typeof UnauthenticatedRouteWithChildren
  '/_authenticated/$username': typeof AuthenticatedUsernameRoute
  '/_authenticated/discover': typeof AuthenticatedDiscoverRoute
  '/_authenticated/players': typeof AuthenticatedPlayersRouteWithChildren
  '/_authenticated/tournaments': typeof AuthenticatedTournamentsRouteWithChildren
  '/_unauthenticated/forgot-password': typeof UnauthenticatedForgotPasswordRoute
  '/_unauthenticated/login': typeof UnauthenticatedLoginRoute
  '/_unauthenticated/reset-password': typeof UnauthenticatedResetPasswordRoute
  '/_unauthenticated/signup': typeof UnauthenticatedSignupRoute
  '/_unauthenticated/verify-email': typeof UnauthenticatedVerifyEmailRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/players/$id': typeof AuthenticatedPlayersIdRoute
  '/_authenticated/tournaments/$id': typeof AuthenticatedTournamentsIdRoute
  '/_authenticated/tournaments/new': typeof AuthenticatedTournamentsNewRoute
  '/_authenticated/venues/$id': typeof AuthenticatedVenuesIdRoute
  '/_authenticated/venues/new': typeof AuthenticatedVenuesNewRoute
  '/_authenticated/feed/': typeof AuthenticatedFeedIndexRoute
  '/_authenticated/players/': typeof AuthenticatedPlayersIndexRoute
  '/_authenticated/tournaments/': typeof AuthenticatedTournamentsIndexRoute
  '/_authenticated/venues/': typeof AuthenticatedVenuesIndexRoute
  '/api/auth/$/$': typeof ApiAuthSplatSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$username'
    | '/discover'
    | '/players'
    | '/tournaments'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/'
    | '/players/$id'
    | '/tournaments/$id'
    | '/tournaments/new'
    | '/venues/$id'
    | '/venues/new'
    | '/feed'
    | '/players/'
    | '/tournaments/'
    | '/venues'
    | '/api/auth/$/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$username'
    | '/discover'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/'
    | '/players/$id'
    | '/tournaments/$id'
    | '/tournaments/new'
    | '/venues/$id'
    | '/venues/new'
    | '/feed'
    | '/players'
    | '/tournaments'
    | '/venues'
    | '/api/auth/$/$'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_unauthenticated'
    | '/_authenticated/$username'
    | '/_authenticated/discover'
    | '/_authenticated/players'
    | '/_authenticated/tournaments'
    | '/_unauthenticated/forgot-password'
    | '/_unauthenticated/login'
    | '/_unauthenticated/reset-password'
    | '/_unauthenticated/signup'
    | '/_unauthenticated/verify-email'
    | '/_authenticated/'
    | '/_authenticated/players/$id'
    | '/_authenticated/tournaments/$id'
    | '/_authenticated/tournaments/new'
    | '/_authenticated/venues/$id'
    | '/_authenticated/venues/new'
    | '/_authenticated/feed/'
    | '/_authenticated/players/'
    | '/_authenticated/tournaments/'
    | '/_authenticated/venues/'
    | '/api/auth/$/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  UnauthenticatedRoute: typeof UnauthenticatedRouteWithChildren
  ApiAuthSplatSplatRoute: typeof ApiAuthSplatSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_unauthenticated': {
      id: '/_unauthenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof UnauthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_unauthenticated/verify-email': {
      id: '/_unauthenticated/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof UnauthenticatedVerifyEmailRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_unauthenticated/signup': {
      id: '/_unauthenticated/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof UnauthenticatedSignupRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_unauthenticated/reset-password': {
      id: '/_unauthenticated/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof UnauthenticatedResetPasswordRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_unauthenticated/login': {
      id: '/_unauthenticated/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof UnauthenticatedLoginRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_unauthenticated/forgot-password': {
      id: '/_unauthenticated/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof UnauthenticatedForgotPasswordRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_authenticated/tournaments': {
      id: '/_authenticated/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof AuthenticatedTournamentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/players': {
      id: '/_authenticated/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof AuthenticatedPlayersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/discover': {
      id: '/_authenticated/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AuthenticatedDiscoverRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$username': {
      id: '/_authenticated/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof AuthenticatedUsernameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/venues/': {
      id: '/_authenticated/venues/'
      path: '/venues'
      fullPath: '/venues'
      preLoaderRoute: typeof AuthenticatedVenuesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tournaments/': {
      id: '/_authenticated/tournaments/'
      path: '/'
      fullPath: '/tournaments/'
      preLoaderRoute: typeof AuthenticatedTournamentsIndexRouteImport
      parentRoute: typeof AuthenticatedTournamentsRoute
    }
    '/_authenticated/players/': {
      id: '/_authenticated/players/'
      path: '/'
      fullPath: '/players/'
      preLoaderRoute: typeof AuthenticatedPlayersIndexRouteImport
      parentRoute: typeof AuthenticatedPlayersRoute
    }
    '/_authenticated/feed/': {
      id: '/_authenticated/feed/'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/venues/new': {
      id: '/_authenticated/venues/new'
      path: '/venues/new'
      fullPath: '/venues/new'
      preLoaderRoute: typeof AuthenticatedVenuesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/venues/$id': {
      id: '/_authenticated/venues/$id'
      path: '/venues/$id'
      fullPath: '/venues/$id'
      preLoaderRoute: typeof AuthenticatedVenuesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tournaments/new': {
      id: '/_authenticated/tournaments/new'
      path: '/new'
      fullPath: '/tournaments/new'
      preLoaderRoute: typeof AuthenticatedTournamentsNewRouteImport
      parentRoute: typeof AuthenticatedTournamentsRoute
    }
    '/_authenticated/tournaments/$id': {
      id: '/_authenticated/tournaments/$id'
      path: '/$id'
      fullPath: '/tournaments/$id'
      preLoaderRoute: typeof AuthenticatedTournamentsIdRouteImport
      parentRoute: typeof AuthenticatedTournamentsRoute
    }
    '/_authenticated/players/$id': {
      id: '/_authenticated/players/$id'
      path: '/$id'
      fullPath: '/players/$id'
      preLoaderRoute: typeof AuthenticatedPlayersIdRouteImport
      parentRoute: typeof AuthenticatedPlayersRoute
    }
    '/api/auth/$/$': {
      id: '/api/auth/$/$'
      path: '/api/auth/$/$'
      fullPath: '/api/auth/$/$'
      preLoaderRoute: typeof ApiAuthSplatSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedPlayersRouteChildren {
  AuthenticatedPlayersIdRoute: typeof AuthenticatedPlayersIdRoute
  AuthenticatedPlayersIndexRoute: typeof AuthenticatedPlayersIndexRoute
}

const AuthenticatedPlayersRouteChildren: AuthenticatedPlayersRouteChildren = {
  AuthenticatedPlayersIdRoute: AuthenticatedPlayersIdRoute,
  AuthenticatedPlayersIndexRoute: AuthenticatedPlayersIndexRoute,
}

const AuthenticatedPlayersRouteWithChildren =
  AuthenticatedPlayersRoute._addFileChildren(AuthenticatedPlayersRouteChildren)

interface AuthenticatedTournamentsRouteChildren {
  AuthenticatedTournamentsIdRoute: typeof AuthenticatedTournamentsIdRoute
  AuthenticatedTournamentsNewRoute: typeof AuthenticatedTournamentsNewRoute
  AuthenticatedTournamentsIndexRoute: typeof AuthenticatedTournamentsIndexRoute
}

const AuthenticatedTournamentsRouteChildren: AuthenticatedTournamentsRouteChildren =
  {
    AuthenticatedTournamentsIdRoute: AuthenticatedTournamentsIdRoute,
    AuthenticatedTournamentsNewRoute: AuthenticatedTournamentsNewRoute,
    AuthenticatedTournamentsIndexRoute: AuthenticatedTournamentsIndexRoute,
  }

const AuthenticatedTournamentsRouteWithChildren =
  AuthenticatedTournamentsRoute._addFileChildren(
    AuthenticatedTournamentsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedUsernameRoute: typeof AuthenticatedUsernameRoute
  AuthenticatedDiscoverRoute: typeof AuthenticatedDiscoverRoute
  AuthenticatedPlayersRoute: typeof AuthenticatedPlayersRouteWithChildren
  AuthenticatedTournamentsRoute: typeof AuthenticatedTournamentsRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedVenuesIdRoute: typeof AuthenticatedVenuesIdRoute
  AuthenticatedVenuesNewRoute: typeof AuthenticatedVenuesNewRoute
  AuthenticatedFeedIndexRoute: typeof AuthenticatedFeedIndexRoute
  AuthenticatedVenuesIndexRoute: typeof AuthenticatedVenuesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedUsernameRoute: AuthenticatedUsernameRoute,
  AuthenticatedDiscoverRoute: AuthenticatedDiscoverRoute,
  AuthenticatedPlayersRoute: AuthenticatedPlayersRouteWithChildren,
  AuthenticatedTournamentsRoute: AuthenticatedTournamentsRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedVenuesIdRoute: AuthenticatedVenuesIdRoute,
  AuthenticatedVenuesNewRoute: AuthenticatedVenuesNewRoute,
  AuthenticatedFeedIndexRoute: AuthenticatedFeedIndexRoute,
  AuthenticatedVenuesIndexRoute: AuthenticatedVenuesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface UnauthenticatedRouteChildren {
  UnauthenticatedForgotPasswordRoute: typeof UnauthenticatedForgotPasswordRoute
  UnauthenticatedLoginRoute: typeof UnauthenticatedLoginRoute
  UnauthenticatedResetPasswordRoute: typeof UnauthenticatedResetPasswordRoute
  UnauthenticatedSignupRoute: typeof UnauthenticatedSignupRoute
  UnauthenticatedVerifyEmailRoute: typeof UnauthenticatedVerifyEmailRoute
}

const UnauthenticatedRouteChildren: UnauthenticatedRouteChildren = {
  UnauthenticatedForgotPasswordRoute: UnauthenticatedForgotPasswordRoute,
  UnauthenticatedLoginRoute: UnauthenticatedLoginRoute,
  UnauthenticatedResetPasswordRoute: UnauthenticatedResetPasswordRoute,
  UnauthenticatedSignupRoute: UnauthenticatedSignupRoute,
  UnauthenticatedVerifyEmailRoute: UnauthenticatedVerifyEmailRoute,
}

const UnauthenticatedRouteWithChildren = UnauthenticatedRoute._addFileChildren(
  UnauthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  UnauthenticatedRoute: UnauthenticatedRouteWithChildren,
  ApiAuthSplatSplatRoute: ApiAuthSplatSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
